-- INSERT INTO
--   users (email, password, admin)
-- VALUES
--   ('lebronJames@clevelandcavs.com', 'password1', false),
--   ('kleankanteen@gmail.com', 'password1', false),
--   ('snapple12@cox.com', 'password1', false),
--   ('admin12@gmail.com', 'password1', true),
--   ('lebronJame8498s@clevelandcavs.com', 'password1', false),
--   ('admin@gmail.com', 'password1', true),
--   ('user@gmail.com', 'password1', false),
--   ('user12@clevelandcavs.com', 'password1', false),
--   ('lebronJames2@clevelandcavs.com', 'password1', false),
--   ('lebronJames4@clevelandcavs.com', 'password1', false)
-- ;
